name: Floresco Photography
favicon: null
layout_spectrum: 0.6830197139643133
typography_spectrum: 0.8828054259065539
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5444198306649923
  lightness: 0.4023757162503898
  saturation: 0.7367996065877378
  rhythmicContrast: 0.4007389124017209
purpose: []
